spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configserver
      failFast: false
  application:
    name: product-service
  profiles:
    active: hau

server:
  port: 8088
# dang ky voi eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}


#logging:
#  level:
#    root: DEBUG




















