server:
  port: 8100

spring:
  application:
    name: currency-calculation-service

# dang ky voi eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka} # đăng ký với eureka server đây là một eureka client
#    fetch-registry: true
#    register-with-eureka: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka